### ISSUE TITLE
Add design token types

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#111]
there's more to add to the bundle to help various transformers and UI represent the values

https://design-tokens.github.io/community-group/format/

**Comment by japneetsingh035** [comment]
Hi @argyleink, I would like to contribute. Can you tell me where to start?

**Comment by argyleink** [comment]
Adding types to "some" of the props is a great place!

Here's a decent spot to add the type information https://github.com/argyleink/open-props/blob/main/src/_create-props.js#L59. 

In that loop you could check if the prop includes the string `--color` and if so, add color type information based on the design token spec. That loop could check for other props and add applicable type information as well. See more about types here https://design-tokens.github.io/community-group/format/#types

Feel free to jump on the discord and ping with additional questions https://discord.gg/nySYDh3H 🙂

**Comment by japneetsingh035** [comment]
Hi @argyleink, I know I made a pull request as a draft, I need more information to understand if this is correct or not, I will wait for your note to understand what more is required. Thank you!
