### ISSUE TITLE
The gradient 5 and gradient 28 has a line.

### ISSUE THREAD

**Issue by handycode** [argyleink/open-props#135]
![10 47 47](https://user-images.githubusercontent.com/5368890/147028429-58e2c9ae-f3fc-4321-9089-fed38e9951ab.png)

```
--gradient-5:conic-gradient(from -270deg at 75% 110%,#f0f,#fffaf0);
--gradient-28:conic-gradient(from -90deg at 50% 105%,#fff,orchid);
```

I fixed it below:

```
--gradient-5:conic-gradient(from -270deg at 74% 110%,#f0f,#fffaf0);
--gradient-28:conic-gradient(from -90deg at 49% 105%,#fff,orchid);
```

![10 47 34](https://user-images.githubusercontent.com/5368890/147028425-d8c55a1a-5c04-4539-98bc-36c19af173c4.png)

**Comment by brittneypostma** [comment]
Is this issue still relevant? I don't see any lines in the gradients currently on ff or chrome. What browser are the screenshots from?

**Comment by argyleink** [comment]
12 in your example also has a line.
it's odd/fishy that the lines are only on conics and seem random. 
can you create a link that reproduces the issue for us to preview? look like you've removed the overflow styles in your screenshot and made swatches from the list 🙂

**Comment by argyleink** [comment]
closing for now, feel free to reopen if/when you find more or have clear reproduction steps
