### ISSUE TITLE
Document the Figma Design Token import workflow

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#146]
see this great example here https://github.com/hchiam/figma-tokens-sync-example

**Comment by argyleink** [comment]
https://unpkg.com/open-props/open-props.figma-tokens.json
https://unpkg.com/open-props/open-props.figma-tokens.sync.json

**Comment by brittneypostma** [comment]
We are currently trying to get this to flow the other way as well at work, from Figma tokens to JSON with the [Figma Design Tokens](https://www.figma.com/community/plugin/888356646278934516/Design-Tokens) plugin.
