### ISSUE TITLE
Container width props based on device sizes

### ISSUE THREAD

**Issue by hunzaboy** [argyleink/open-props#155]
For designing layouts, sometimes its necessary to have width for containers. It makes the layout  flow easy to understand and manage. It would be helpful to have these devices sizes as container props based on the existing responsive values.

![open-props](https://user-images.githubusercontent.com/827098/150491909-d9159123-b4cd-4c35-b9b6-22aa7062b697.png)

To keep the current naming convention we can have something like:

`--size-container-xxs : 240px`, 
`--size-container-xs: 360px`, 
`--size-container-sm: 480px`, 
`--size-container-md: 768px`, 
`--size-container-lg: 1024px`, 
`--size-container-xl: 1440px`
`--size-container-xxl: 1920px`

These can be individual prop packs.

**Comment by argyleink** [comment]
this is a great idea, thanks for bringing it up! 🙂  
def works best imo as a prop pack. i think this work could be done swiftly! 

curious your thoughts on naming them like this, removing the word container? 
more abstract so maybe more use cases?

```css
--size-xxs: 240px;
--size-xs:  360px;
--size-sm:  480px;
--size-md:  768px;
--size-lg:  1024px;
--size-xl:  1440px;
--size-xxl: 1920px;
```

to me, this make the sizes match the previous naming style closer and doesnt imply any use cases, just a straight port of the media query t-shirt sizes style values into usable prop utilities.

**Comment by hunzaboy** [comment]
Yes, i agree. We don't need the container word.

**Comment by hunzaboy** [comment]
@argyleink , should i add them to the props.media.css or the props.sizes.css. The sizes files already exists so not sure where these props should go? I can create a PR for it once you confirm it.  I think props.sizes.css seems to make more sense. wdyt?

**Comment by argyleink** [comment]
[at the end of the sizes props](https://github.com/argyleink/open-props/blob/main/src/props.sizes.js#L38) yeah! make sure to edit the js file, the css file is generated from that JS 👍🏻
