### ISSUE TITLE
Docs: PostCSS JIT Props + custom media-props

### ISSUE THREAD

**Issue by benbender** [argyleink/open-props#174]
In the following scenario:
 - usage of `open-props` via `postcss` with `postcss-jit-props`
 - and **not** including `normalize.css`

The `--custom-media`-props from `media.css` seem to be stripped out by `postcss-jit-props`. 

If you think about it, it seems to be like expected behaviour, but it took me a moment to realize, because `media.css` is included in `open-props`'s `index.css` by default and it doesn't seem to be related to normalization. I think it might be a good hint for the documentation though.

**Comment by argyleink** [comment]
i think i can help!

tldr; the docs should say that when importing `postcss/normalize` that you also will be importing the media props? Furthermore, if you stop using the postcss normalize src file than you'll need to explicitly import the media props `open-props/media` if you intend to keep using them in queries?

**Comment by benbender** [comment]
The latter was the one that got me stuck. When I removed `normalize`, my `custom-media`-styles stopped working and I had initially no clue why. That's the missing spot in the docs from my pov.
