### ISSUE TITLE
having place-self: flex-start; on buttons.css means it ignores align-items of a flex parent

### ISSUE THREAD

**Issue by andystevenson** [argyleink/open-props#182]
I tried lining up a few buttons in a flex wrapper but the place-self: flex-start overrides a parent align-items. Perhaps the default would better be place-self: inherit; ?

**Comment by argyleink** [comment]
yay, this is a great topic. are you able to share a small demo example? i'm pretttty sure i know what you mean, could i see it though? 

the reasoning was so buttons were "shrink wrapped" by default, but you could stretch them into block items. you're saying tho it's unintuitive to directly target a child for alignment when the parent can supply it right? somethin like that? 🙂

**Comment by andystevenson** [comment]
Hi Adam,

I forked your Open Props Buttons on codepen and added a big circle SVG as the first item in the  article.fluid-flex container. Even though the fluid-flex has place-content: center; the buttons don't line up with the center of the circle. I had to add a .fluid-flex > * { align-self: center; } to center the buttons. (I commented the align-self out in the CSS so you could see the issue straight away.)

https://codepen.io/andystevenson/pen/oNoYyOa

**Comment by argyleink** [comment]
yep this is tough, the default for a button in a flex container shouldnt be stretch.. but by undoing that i've made you have to reach onto a childs self alignment to get the job done. tldr; its supposed to be helpful but ends up getting in the way and you would have corrected it anyway.

**Comment by argyleink** [comment]
i tried all sorts of stuff, the closest to me thinking was ok was also a bizarre hack, and i just overall dont want these buttons to bring a style that has to be undone most the time. thanks! i think this is a nice refinement. 

fixed in `v1.3.4`

**Comment by andystevenson** [comment]
Thanks Adam, the fix looks like a great compromise to me.
