### ISSUE TITLE
postcss-jit-props in Angular 13

### ISSUE THREAD

**Issue by Mac-DevOSYandex** [argyleink/open-props#202]
I'd like to know if it is possible to implement postcss-jit-props in Angular 13 by adding a config file in the root/dir or, is that not possible at the moment? Any plans...? It seems it's a desirable alternative to Angular's own solution.

**Comment by argyleink** [comment]
interesting yeah, i think I'd need a scss plugin for an angular 13 project, as scss is the first class citizen there. it was [quick to get Open Props in](https://stackblitz.com/edit/angular-ivy-gja1sj?file=src%2Fstyles.css), unless..
1. scss runs as it does now
2. you use props but never import them anywhere
3. run postcss with jit-props against the bundle output from scss
4. import that into angular..? 

i dunno. 

i think you'll have bigger perf issues than too many props shipped. you could also go the individual import route and just grab sizes, or one of the colors, etc?
