### ISSUE TITLE
media queries not working

### ISSUE THREAD

**Issue by 7flash** [argyleink/open-props#207]
I added postcss.config.js - but still no effect, any more configuration steps are required?

**Comment by argyleink** [comment]
yeah, once you have a config you can pass it plugins, [this one](https://github.com/postcss/postcss-custom-media) will recognize the media queries and transform them 👍🏻  you're almost there!

**Comment by SalahAdDin** [comment]
> yeah, once you have a config you can pass it plugins, [this one](https://github.com/postcss/postcss-custom-media) will recognize the media queries and transform them 👍🏻 you're almost there!

Well, It comes by default on `postcss-preset-env` and even so, it is not working for me!

**Comment by argyleink** [comment]
i'm back from vacation, did you find a solution to this? it can be tricky as the plugin needs to have the media queries at build time for many configurations, as they [show here](https://github.com/csstools/postcss-custom-media?tab=readme-ov-file#importfrom).

too bad we dont just have this in CSS yet!
