### ISSUE TITLE
Figma plugin to add colors and sizes for the designer

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#21]

**Comment by hchiam** [comment]
Some links that might be helpful:

https://www.figma.com/plugin-docs/setup/

https://help.figma.com/hc/articles/360039958874-Make-plugins-for-the-Figma-Community

**Comment by hchiam** [comment]
there's even a visual UI to create plugins and plugin templates! https://help.figma.com/hc/articles/360042786733

**Comment by hchiam** [comment]
@argyleink, you're thinking of autocomplete, just like in VSCode https://github.com/argyleink/open-props/issues/28, right? so if someone's in figma they can type `var(--pi` and then it'll suggest something like `var(--pink-0)`? (or a list)

Simulated autocomplete:
<img width="456" alt="simulated_autocomplete" src="https://user-images.githubusercontent.com/18131787/147791168-f5eb5ce7-077d-481c-b0c3-3aa045143916.png">

**Comment by argyleink** [comment]
more like importing tokens, like shown here https://jansix.at/resources/figma-tokens. maybe we piggy back on [that plugin](https://jansix.at/resources/figma-tokens) and offer a format it accepts and makes readily available to designers?

**Comment by hchiam** [comment]
oh wow, that's an awesome figma plugin! we can generate open-props tokens into a json file and then paste it into figma tokens JSON tab, or hit the Import button

**Comment by hchiam** [comment]
i could work on creating a script like _create-props.js or pass an option to it, then add a `script` named `"gen:figma"` (or `"gen:tokens"`?)﻿

**Comment by argyleink** [comment]
fixed by #144
