### ISSUE TITLE
<form> focus style is clipped and jagged in Safari

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#212]
https://user-images.githubusercontent.com/1134620/159728510-4f7fd6ea-2ecf-443c-81c8-840f551ccdab.mp4

**Comment by mrtuvn** [comment]
outline: 0 for input that not disabled may help for such case

**Comment by argyleink** [comment]
`wont fix`, see https://github.com/argyleink/open-props/pull/244#issuecomment-1179653685

**Comment by argyleink** [comment]
fixed in Safari Tech Preview
