### ISSUE TITLE
open-props/normalize renders text-underline-offset differently across browsers

### ISSUE THREAD

**Issue by cdvillard** [argyleink/open-props#245]
Nothing wrong with a normalize that doesn't 100% perfectly normalize across all browsers, but I did notice that across Firefox and Chrome that `text-underline-offset` was rendering differently. 

![image](https://user-images.githubusercontent.com/6250214/177553435-0f63be5e-8025-4794-8186-2a734bc4344e.png)

Both inspectors are analyzing anchor elements inheriting the same `text-underline-offset`, but the different shows in how Chrome renders the underline significantly lower than Firefox. Is this because of the differences between the render engines? Is this something we can smooth out somehow in stylesheets?

**Comment by argyleink** [comment]
that's def poopy that [`1px`](https://github.com/argyleink/open-props/blob/main/src/extra/normalize.css#L72) is causing so much issue here lol. we could try and smooth things out in our stylesheets, did you try? i'm feeling inclined to leave it.. but i'd be open to alternative value propositions if they render more predictably.

**Comment by cdvillard** [comment]
I haven't yet, but thought I'd drop a line first to see if this was
already-tread ground. I'll take a look when I can and see what I can come
up with. Feel free to close this if you wish. Otherwise, I might use this
to track and document the effort.

**Comment by argyleink** [comment]
no worries, this is totally "can't unsee". i'm trying some stuff in browser right now:

<details>

Firefox:
![Screen Shot 2022-07-06 at 10 19 25 PM](https://user-images.githubusercontent.com/1134620/177697459-a653c4ae-3e18-47e3-bb11-649154c31bbe.png)

Chrome:
![Screen Shot 2022-07-06 at 10 19 29 PM](https://user-images.githubusercontent.com/1134620/177697463-328285a7-0dba-4e08-9c5c-f162b2a4c75e.png)

Safari:
![Screen Shot 2022-07-06 at 10 23 20 PM](https://user-images.githubusercontent.com/1134620/177697712-5bcc345d-f8ba-45fd-9cd4-1e882af81bc9.png)


<summary>default / user agent screenshots</summary>

</details>

<details>

<summary>open props normalized</summary>

Firefox:  
(yeah, it's like it needs to be `2px` for Firefox, to actually be normalized)
![Screen Shot 2022-07-06 at 10 19 48 PM](https://user-images.githubusercontent.com/1134620/177697955-dff008de-6e96-4ec6-abb1-e8e1709e0e4b.png)


Chrome:
![Screen Shot 2022-07-06 at 10 19 38 PM](https://user-images.githubusercontent.com/1134620/177697931-3fb8fda0-6e62-44c5-8425-6d9f9bdee53d.png)


Safari:  
(looks the same, `1px` is the default)
![Screen Shot 2022-07-06 at 10 23 20 PM](https://user-images.githubusercontent.com/1134620/177697857-8bcdc93b-d59c-4a6b-aa7d-4dabe0fd723b.png)


</details>

<details>

<summary>proposed fix: adjust firefox to `2px`</summary>

Firefox:  
![Screen Shot 2022-07-06 at 10 28 40 PM](https://user-images.githubusercontent.com/1134620/177698513-6343f1d6-1e59-4a98-85b3-ea043fda5ae1.png)



Chrome:
![Screen Shot 2022-07-06 at 10 19 38 PM](https://user-images.githubusercontent.com/1134620/177697931-3fb8fda0-6e62-44c5-8425-6d9f9bdee53d.png)


Safari:  
![Screen Shot 2022-07-06 at 10 23 20 PM](https://user-images.githubusercontent.com/1134620/177697857-8bcdc93b-d59c-4a6b-aa7d-4dabe0fd723b.png)


</details>

**Comment by argyleink** [comment]
checkout https://open-props--pr246-245-open-propsnormal-4mllu3ov.web.app/, it's got an updated value for firefox. thoughts?

**Comment by cdvillard** [comment]
Works for me. Pretty simple solution, all things considered.
