### ISSUE TITLE
More dark colors

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#247]
It's the only thing about Open Color I don't like so far is the lack of a few darker colors. Well, turns out I'm not alone and the work has been done here! https://github.com/fchristant/colar

Need to decide if these should ship sooner than later, or wait for relative color syntax to make this a dynamic task instead of one with all the presets. 🤔 

https://github.com/yeun/open-color/issues/119

**Comment by LuukLeijtens** [comment]
The [Mantine ui](https://mantine.dev/theming/extend-theme/#default-colors) libary also has a dark variant based on open colors

**Comment by kelvindecosta** [comment]
+1 for this!
