### ISSUE TITLE
Add `--ease-anticipate-*` easings

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#248]
these would be complimentary to `--ease-elastic-*` in that elastic easing ends with a bounce and the anticipate easings would start with a bounce. we have `--ease-squish-*` which bounces both sides also. so adding these easings would give folks that disney type [anticipatory animation](https://www.joshuanava.biz/disney-animation/anticipation.html) start. 

this task is to add 5 more easings that should be very similar to elastic

todo:
- [ ] add 5 new props
- [ ] update docsite with new props

**Comment by argyleink** [comment]
a strong proposal by Jhey is to name it `--ease-elastic-in-*` 👍🏻  the only bummer is it might mean renaming the other elastic easings and creating a breaking version. i think i'm down with the tradeoff tho, cuz this looks nice:

```css
/* today */
--ease-elastic-3
--ease-anticipate-3 (to do)
--ease-squish-3

/* proposed breaking change */
--ease-elastic-out-3
--ease-elastic-in-3
--ease-elastic-in-out-3
```

**Comment by argyleink** [comment]
`--ease-windup-*` is another contender

**Comment by argyleink** [comment]
```css
--ease-out-elastic-3
--ease-in-elastic-3
--ease-in-out-elastic-3
```

**Comment by 621alexl** [comment]
Working on this now for TS Open.
