### ISSUE TITLE
Automate bundle size report in docsite

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#25]
not so bad manually compressing and updating values, but would be sweet to automate the lib sizes and feed them into a build system

**Comment by roblevintennis** [comment]
This also relates to my questions on Discord. It sounds like purging is not on the horizon, yah? I think docs on a recommended approach for crusty folks like myself that want to avoid importing absolutely everything would be great too.

**Comment by argyleink** [comment]
purging if offloaded to purgecss as part of a production build. i dont have that documented on the site no, it's also not that reliable. if you're worried about overshipping props, consider the postcss-jit-props plugin which additively puts the props into your stylesheet when used, or only import the groups of props you want (colors, sizes, etc). 

this partically issue #25 is about automating the bundle sizes tho, not about how to reduce bundle sizes in your own builds.

**Comment by bjorntheart** [comment]
@argyleink Don't know if this is what you're after, but I wrote a little script that checks the current size of the built `props.<thing>.css` files in `src`. It shows the _current file size_ and also the _brotli_ and _gzip_ sizes. I imagine this could be generated in a Github action, and perhaps added to the release changelog

Here is an example of the output
<img width="439" alt="Screenshot 2024-02-17 at 20 38 27" src="https://github.com/argyleink/open-props/assets/53244/72048365-d075-421e-8312-b0e3e902fa26">

**Comment by argyleink** [comment]
nice, that data as json would be great. i could tuck it into an npm script then use the data with vite to populate the sizes. i dont have any time to do it right now, but just having that script in package.json would be nice.
