### ISSUE TITLE
New bloom fade-in animation

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#255]
https://twitter.com/shuding_/status/1552438750470340610?s=20&t=95DjzncWa9CBSwEJkLBCbQ

**Comment by hchiam** [comment]
I'm looking into this. How about both a fade-in-bloom and a fade-out-bloom?

**Comment by argyleink** [comment]
nice yessss, fade-out toooo

**Comment by argyleink** [comment]
closed by #260
