### ISSUE TITLE
docsite bottom gap (because of browser bottom bar)

### ISSUE THREAD

**Issue by hchiam** [argyleink/open-props#264]
open https://open-props.style in Firefox on mobile Android, which has the url bar on the bottom. 
When scrolling down, or when finding text on the page, the bottom bar disappears, which causes the website's scroll nav to have a gap on the bottom: 
<img alt="gap when searching text" src="https://user-images.githubusercontent.com/18131787/184249269-d7d06d03-29af-440e-a0e1-91691b4dfba2.png" width="300"> <img alt="gap when scrolling down" src="https://user-images.githubusercontent.com/18131787/184249275-684a8fc5-b184-4f92-9157-c6c54283fc95.png" width="300">

**Comment by hchiam** [comment]
I'll see if I can figure this out.

**Comment by argyleink** [comment]
strange cuz firefox on mobile should be firefox desktop, but looks like a delta in behavior.. curious how much control you'll have over a fix! thx for takin a peek at it 🙂

**Comment by hchiam** [comment]
yeah, it's a default mobile setting: 
(bottom and scroll to hide are on by default) 

<img src="https://user-images.githubusercontent.com/18131787/185032940-141c09a2-80dd-4104-bdd9-46f5074dbd5d.png" alt="screenshot of Firefox mobile settings" width="300"> 

I tried looking into a fix but it might not be worth making a heavy-weight fix that slows down the majority of users, so I'll close this ticket as a "won't fix" for now.
