### ISSUE TITLE
It can combine with CSS-in-JS?

### ISSUE THREAD

**Issue by kacMadushan** [argyleink/open-props#267]
**Open Props is super awesome** and CSS variables easy to manage styling and useful. 
but my issues is it can combine with any  CSS-in-JS libraries ?

**Comment by argyleink** [comment]
you can! the props are also importable from javascript for use as static values within css-in-js

```js
import OpenProps from 'open-props';

console.log(OpenProps.size3);
console.log(OpenProps.gradient5);
console.log(OpenProps['--size-3']);
```

you could also import the props globally in a main CSS file, then use them in your css-in-js as css variables

**Comment by kacMadushan** [comment]
Yah it's so cool 

`import { createGlobalStyle } from 'styled-components';
import Colors from 'open-props/src/colors';
import Fonts from 'open-props/src/fonts'

export const GlobalStyles = createGlobalStyle`
  body {
    background-color: ${Colors['--gray-9']};
    color: ${Colors['--gray-0']};
    font-size: ${Fonts['--font-size-3']};
  }
`;`

thanks argyleink
