### ISSUE TITLE
Include theme toggling in normalize.css

### ISSUE THREAD

**Issue by Crisfole** [argyleink/open-props#286]
I spent a good deal of time trying to figure out why `data-theme=light` and `data-theme=dark` didn't work in normalize.

As it turns out, it's not included at all; I think it'd be pretty reasonable to add to `normalize.css` and largely would just mean duplicating all the `@media (--OSDark)` and `@media (--OSLight)` rules with the `@nest [data-theme=dark] &` and `@nest [data-theme=light] &` rules.

Last I checked CSS does not allow alternation between `@media` rules and other selectors, but POSTCSS might have something for that? That would make it even easier.

**Comment by argyleink** [comment]
good call, this should totally be provided in the package for easy use 👍🏻 

what do you think of just adding 2 more imports?

```css
@import "open-props";
@import "open-props/normalize";
@import "open-props/theme/light";
@import "open-props/theme/dark";
```

those theme imports would bring in just the `[data-theme="dark"]` duplication needed to have clientside exceptions. This was it doesn't impact any of the current files and is an additive feature for when folks want to deploy a theme toggle? I could add it to [this PR](https://github.com/argyleink/open-props/pull/285) which is adding "light only" or "dark only" normalize options. Or, you could continue with your PR, add the 2 new files and that'd be it?!

**Comment by argyleink** [comment]
fixed in v1.4.17 👍🏻

**Comment by Crisfole** [comment]
Is this documented? Did you stick with “theme”?

**Comment by argyleink** [comment]
it's not really documented yet nope. i should make a demo and then add some prose to the docsite. will do soon in #304

`@import "open-props/switch/light";` or `@import "theme.light.switch.min.css";`
`@import "open-props/switch/dark";` or `@import "theme.dark.switch.min.css";`
