### ISSUE TITLE
:visited state of anchors has specificity

### ISSUE THREAD

**Issue by rienheuver** [argyleink/open-props#298]
Anchors in open-props of zero specificty: `:where(a[href])`, but their visited state does not: `:where(a[href]):visited` even though I believe it could be `:where(a[href]:visited)`. Correct me if I'm wrong ;-)

This of course hardly ever poses a problem, except when you're building an extensible component-library on top of open-props which you want to have zero-specifity as well :P So I gave it the full where-clause and therefore open-props was more specific.

Anyway, let me know if you want me to make a PR for this :smile:

**Comment by argyleink** [comment]
this one stinks, i think it's a bug in the nesting plugin

**Comment by rienheuver** [comment]
Could it have something to do with transpiling `:where(a):where(:visited)` instead of (:where(a:visited))`? Not that they should make a difference, but perhaps the latter is handled correctly

**Comment by argyleink** [comment]
> Could it have something to do with transpiling `:where(a):where(:visited)` instead of (:where(a:visited))`? Not that they should make a difference, but perhaps the latter is handled correctly

i tried a few nesting combos to see if i could get the results I wanted, but i could certainly try again. maybe to fix it, we dont use nesting and just hand write it so we dont rely on the preprocessor.

**Comment by rienheuver** [comment]
That last suggestion always works of course. Are there any other places where this transpilation error occurs you think now that you know of this one?

**Comment by argyleink** [comment]
> That last suggestion always works of course. Are there any other places where this transpilation error occurs you think now that you know of this one?

this is the only one I've seen so far

**Comment by argyleink** [comment]
found it, nipped it
