### ISSUE TITLE
Add a brown palette

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#308]
![image](https://user-images.githubusercontent.com/1134620/199600240-b9a0a22e-0fce-4388-a7e7-405620591688.png)

from https://twitter.com/jobosonchisa/status/1587825975684890626?s=20&t=qHNaa3oE6M_cg2s46p0eBg

**Comment by argyleink** [comment]
or consider moving from open-color to colar because it's done all the work i was planning on doing https://github.com/fchristant/colar

**Comment by kelvindecosta** [comment]
Hey @argyleink, 

I think switching to `colar` is a great idea!
Love the "feel" of the new palette.

It would also address the issue of the current palette's limited choice of dark colors #247 

I'd be happy to help with the migration.

Thank you for maintaining this awesome project!

**Comment by argyleink** [comment]
fixed in 1.5
