### ISSUE TITLE
Trivial annoyance: 4 Color Schemes demo naming inconsistent with normalize

### ISSUE THREAD

**Issue by wrex** [argyleink/open-props#325]
First off: **WOWZA THIS SYSTEM IS GREAT!!**

(Couldn't hold back, I never thought CSS could be this much fun. Whee!)

While playing around with theming, I copied the CSS in the "4 Color Schemes" demo in the "Built with Open Props" section of the home page into my local mockup. Unfortunately, my headings weren't showing up with the appropriate theme. It took me a while to track down the issue.

I didn't realize it, but I'd accidentally imported normalize in addition to the other imports at the top of the codepen demo. Normalize uses custom properties like `--text-1` and `--text-2`, while the demo uses `--text1` and `--text2` (without the dash before the number).

In the unlikely case someone else runs into the same issue, it might be worth updating the css in the codepen to use the same naming convention.

**Comment by argyleink** [comment]
fixed! let me know if i missed anything 🙂 

glad you're diggin it ❤️

**Comment by argyleink** [comment]
oh poo, action had an issue deploying. it'll be fixed on the docsite once i resolve this action issue 😅

**Comment by argyleink** [comment]
all goooood

**Comment by wrex** [comment]
Confirmed. Looks good to me. Thanks!
