### ISSUE TITLE
type definitions?

### ISSUE THREAD

**Issue by mayank99** [argyleink/open-props#333]
when using the JS api:
- there is no autocomplete for any of the props
- importing in a `.ts`/`.tsx` file results in an error 

![](https://user-images.githubusercontent.com/9084735/212214496-0dab7d55-3ee9-4e6c-82c8-17c1ef227f4a.png)
![](https://user-images.githubusercontent.com/9084735/212214074-6981e34d-1564-46f1-80b5-30684aefac81.png)

i can contribute by either adding `.d.ts` files or by converting the codebase to all `.ts`

**Comment by mayank99** [comment]
searching for open PRs, i found #223 and #225. i'll have a look at those and see if i can help with either or start from scratch

**Comment by argyleink** [comment]
autocomplete would def be nice, you've seen the other PRs, def the highest demanded feature missing from OP. thanks for throwin your hat in the ring to add it 🙂 

> importing in a .ts/.tsx file results in an error

can i learn more about this? working fine [here](https://stackblitz.com/edit/react-vanillaextract-openprops?file=src%2Fcomponents%2Fbutton%2Fbutton.css.ts)?

test with this:

```js
import colors from 'open-props/src/colors';
console.log(colors);
```

**Comment by mayank99** [comment]
> > importing in a .ts/.tsx file results in an error
> 
> can i learn more about this? working fine [here](https://stackblitz.com/edit/react-vanillaextract-openprops?file=src%2Fcomponents%2Fbutton%2Fbutton.css.ts)?
 
i see the same error in that example.
<img width="509" alt="" src="https://user-images.githubusercontent.com/9084735/212403726-c35e8410-ac03-441a-a0a1-d2ebaaad2f97.png">

> test with this:
> 
> ```js
> import colors from 'open-props/src/colors';
> console.log(colors);
> ```

<img width="358" alt="" src="https://user-images.githubusercontent.com/9084735/212404185-dd2a7c8a-cc1b-411e-9e96-1ec13a62779d.png">

i should also clarify that TS errors are nonblocking, just annoying - they do not make the actual build fail (unless running `tsc` along with the build) and can also be `ts-ignore`d easily.

**Comment by argyleink** [comment]
ohh i see, the TS error, i thought the module was failing to import. ok, much less severe!
