### ISSUE TITLE
Nuxt 3 - Usage with postcss-jit-props

### ISSUE THREAD

**Issue by smastrom** [argyleink/open-props#340]
Sorry if I post here but I couldn't find a better place, maybe it will help someone. Please close this issue if this is a mistake.

1. Install the plugin and this package:

``` bash
pnpm add postcss-jit-props open-props -D
```

2. Edit nuxt-config.ts:

```js
import OpenProps from 'open-props';

export default defineNuxtConfig({
  postcss: {
    plugins: {
      'postcss-jit-props': OpenProps,
    },
  },
});
```

**Comment by argyleink** [comment]
yep, that was a bit frustrating to add, but here's it all figured out for ya!

https://stackblitz.com/edit/nuxt-openprops
