### ISSUE TITLE
Why TS definition doesn't export --surface-* attributes?

### ISSUE THREAD

**Issue by tleperou** [argyleink/open-props#349]
Hi there

🙌 

Quick question about the reason to omit the `--surface-*` attributes from the export of `open-props.module.d.ts`.

Am I right to think that was made on purpose?

Thanks guys for this great package!

**Comment by tleperou** [comment]
Cause `--surface` depends on the `prefers-color-scheme`, it can't be properly exported i TDS definitions 🤔

**Comment by argyleink** [comment]
hi! great question ❤️ 

the props from normalize are "extra", they're not part of the main package of OP. they're special for users of the normalize. Might be confusing if someone was using OP and saw a suggestion for --surface-1, even tho it wasnt actually loaded by their tools.

**Comment by tleperou** [comment]
Closing, got an answer 🚀
