### ISSUE TITLE
Add link to this color helper in docsite 

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#354]
https://props-color-finder.netlify.app

**Comment by kaf-lamed-beyt** [comment]
@argyleink I can take this, if you'd love me to.

I'm thinking of creating a section just after "Tooling", below — for projects built with open-props, more like a showcase of some sort.

https://github.com/argyleink/open-props/blob/58a52be43251681e23678d4b93df898a569b51d3/docsite/index.html#L3491

Or I can just add it to the tooling div without any hassle. Please let me know which one sounds good.

**Comment by argyleink** [comment]
hey thanks! yeah, i think that's a great spot 👍🏻 

add a new div and `<dt>Showcase</dt>`, we'll start piling showcase links in there 🚀

**Comment by kaf-lamed-beyt** [comment]
Awesome!! 

I'll do that now. 🚀
