### ISSUE TITLE
Docsite: Color Theming 101 Typo

### ISSUE THREAD

**Issue by roryhen** [argyleink/open-props#364]
Just a super small thing I noticed, since I copied the demo values, the gray values used for `--surface-{1-4}-light` are slightly out of order:
![image](https://user-images.githubusercontent.com/35480205/231212697-9f846a4e-3ebe-4850-a2d1-24ad729c2233.png)

It's a super helpful aside, really demonstrates the power of css custom properties, thanks for all the hard work!

**Comment by argyleink** [comment]
thanks, fixed it!
