### ISSUE TITLE
JIT props plugin documentation needs correction

### ISSUE THREAD

**Issue by hirasso** [argyleink/open-props#367]
Hi there! I wasn't able to get the postcss-jit-props plugin to work based on the documentation: 

```js
// postcss.config.js
const postcssJitProps = require('postcss-jit-props');
const OpenProps = require('open-props');

module.exports = {
  plugins: [
    postcssJitProps({
      files: [
        require('open-props/open-props.min.css'),
      ]
    }),
  ]
}
```
This snippet has two problems:
1. the file shouldn't be `require`d (otherwise postcss will try to compile it, leading to errors)
2. the file path needs to be absolute

This worked for me:
```js
const postcssJitProps = require('postcss-jit-props');
const path = require('path');

module.exports = {
	plugins: [
		postcssJitProps({
			files: [
				path.resolve(__dirname, 'node_modules/open-props/open-props.min.css'),
			]
		}),
	]
}
```
Can someone confirm this? I'd submit a PR for the docs if you want one :)

**Comment by argyleink** [comment]
nice catch! PR would be great 🙂 [here's the LOCs](https://github.com/argyleink/open-props/blob/main/docsite/index.html#L1043-L1057) to update to your fixed snippet.

**Comment by hirasso** [comment]
Created a PR.
