### ISSUE TITLE
`npm run test` failing

### ISSUE THREAD

**Issue by hirasso** [argyleink/open-props#371]
If I try to run the tests, I get the following error:

```bash
❯ npm run test

> open-props@1.5.8 test
> ava test/basic.test.cjs


  Should produce shadow :host props

  test/basic.test.cjs:40

   39: test('Should produce shadow :host props', async t => {  
   40:   t.assert(fs.existsSync('./open-props.shadow.min.css'))
   41:   t.assert(fs.existsSync('./easings.shadow.min.css'))   

  Value is not truthy:

  false

  › test/basic.test.cjs:40:5

  ─

  1 test failed
```

**Comment by hirasso** [comment]
Ah I see. First need to run `npm run bundle`. Maybe that should be done automatically when exectuting `test`?

```json
{
  "test": "npm run bundle && ava test/basic.test.cjs",
}
```

**Comment by argyleink** [comment]
We could switch to that yeah. Could set it up using package.json pre script syntax too:

```
{
  "pretest": "npm run bundle",
  "test": "ava test/basic.test.cjs",
}
```

reason i dont have it now is i find it can be surprising and maybe resource wasteful to run the bundle every time before running tests. 🤷🏻 

we'd also need to update actions and CI to be aware of the automated bundling before testing.

do you want to switch this issue to a workflow/feature request?

**Comment by hirasso** [comment]
Ey ended up not using Open Props in my project. So I'd like to hand this over to the maintainers of this project.
