### ISSUE TITLE
Header size block inline-size doesn't match example text block inline-size

### ISSUE THREAD

**Issue by brandonpittman** [argyleink/open-props#385]
https://github.com/argyleink/open-props/blob/38d2d8c396b0aaec1ba01b89a91f0990845ab1c6/docsite/index.html#L2967-L2969

<img width="1170" alt="CleanShot 2023-06-30 at 1 51 22@2x" src="https://github.com/argyleink/open-props/assets/967145/5df46050-361c-425a-b0d5-94a1b4b3e0ac">

The `--header-size` example blocks don't have the same font-size or font-weight as the examples beneath them. They would need 

```html
<div style="inline-size: var(--size-header-1); font-size: var(--font-size-3); font-weight: var(--font-weight-9);" />
```

**Comment by argyleink** [comment]
ty for this tip! fixed 👍🏻
