### ISSUE TITLE
Docs display wrong values for prefers-contrast media query

### ISSUE THREAD

**Issue by wojciechczerniak** [argyleink/open-props#386]
Hi,

I've noticed that docs page has a typo. Values shown are not valid for this media feature

Website example:
https://github.com/argyleink/open-props/blob/45a735169c62544a176b1d95384aeaf00d81862e/docsite/index.html#L3273-L3274

Real values:
https://github.com/argyleink/open-props/blob/45a735169c62544a176b1d95384aeaf00d81862e/src/props.media.css#L11-L12

Fix for index.html:
```diff
-@custom-media --highContrast  (prefers-contrast: high); 
+@custom-media --highContrast  (prefers-contrast: more); 
-@custom-media --lowContrast   (prefers-contrast: low); 
+@custom-media --lowContrast   (prefers-contrast: less); 
```

**Comment by argyleink** [comment]
ty!
