### ISSUE TITLE
Inset shadows should have very subtle bottom compliments

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#391]
see this https://codepen.io/argyleink/pen/yLEVdEX

both a top black shadow and a bottom highlight, should be in both the dark and light mode inset shadows

**Comment by Vidhanvyrs** [comment]
hey @argyleink  I would like to contribute in this issue. Can you assign me?

**Comment by argyleink** [comment]
thank you, hope its fun! ask any questions you need here, or find me on the discord 👍🏻

**Comment by Vidhanvyrs** [comment]
so you want this shadow to be applied to this only
![image](https://github.com/argyleink/open-props/assets/94836010/95104329-0906-4b19-a1dd-ccfac0f54c60)
or this all too 
![image](https://github.com/argyleink/open-props/assets/94836010/a589060a-42cd-4815-8d51-f8a087c85c8a)

**Comment by argyleink** [comment]
just [these inner ones](https://open-props.style/#shadows):

![Screenshot 2023-08-18 11 10 11 AM](https://github.com/argyleink/open-props/assets/1134620/f0c17f73-b631-4138-a795-c8aa9ad2357b)

it's about adding the highlight to the bottom of the shadow, by adding something like this `inset 0 -.5px 0 0 #fff1` to [these inner shadows](https://github.com/argyleink/open-props/blob/main/src/props.shadows.js#L42-L45).

Here's kinda what I was thinking (prototyped in the browser). it's very subtle, you may even have to zoom it, but there's a subtle 1px highlight at the bottom of the boxes in this screenshot:

![image](https://github.com/argyleink/open-props/assets/1134620/d88345e5-c791-4133-b2ba-41ea050694c0)

maybe its too subtle?
maybe `-.5px` should be `-1px`?
what happens in the light theme, do things needs adjusted?

**Comment by Vidhanvyrs** [comment]
hey @argyleink  I came up with the asked solution please check the PR and suggest changes if any required 😄
