### ISSUE TITLE
Adapter for Panda

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#407]
https://panda-css.com/docs/theming/tokens

"largely influenced" means you can [copy a ton of this work](https://github.com/argyleink/open-props/blob/main/build/to-tokens.js)

**Comment by indaco** [comment]
#433 could be reusable here!

**Comment by argyleink** [comment]
fixed by the PandaCSS team 👍🏻 
https://stackblitz.com/edit/pandacss-open-props-fs423z?file=src%2FApp.tsx

**Comment by argyleink** [comment]
`@pandacss/preset-open-props`
