### ISSUE TITLE
Large durations

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#415]
### Discussed in https://github.com/argyleink/open-props/discussions/398

<div type='discussions-op-text'>

<sup>Originally posted by **argyleink** August 28, 2023</sup>
Usage like `var(--1day)` or something 

- 1minute
- 5minutes
- .5hour
- .5day
- 1day
- 2days
- 1week
- etc

Def be a non-main bundle package, but nice to import if needed, and also cool to have in the jit-props set

Or is this a job for custom units?</div>

**Comment by yurimutti** [comment]
I would like to work in this issue, can you explain more and assign to me ?
