### ISSUE TITLE
Border radius at table

### ISSUE THREAD

**Issue by Tihomir971** [argyleink/open-props#440]
:where(table thead th:first-child) {
border-top-left-radius: var(--nice-inner-radius);
}
Last child also

It should be set only on first row in header (someone can have more then one row)

**Comment by argyleink** [comment]
i'm interested in this! but can you provide a demo example showing the issue and the resolution? i'm pretty sure i know what youre saying but i'd appreciate seeing it 🙂

**Comment by argyleink** [comment]
fixed in `v1.6.14`
