### ISSUE TITLE
Sizes Counters Wrong

### ISSUE THREAD

**Issue by Crisfole** [argyleink/open-props#481]
<img width="104" alt="image" src="https://github.com/argyleink/open-props/assets/413237/5e675d8a-eaa7-4dfc-9331-ac3c2bf86539">

Looks like you need a different strategy for the sizes counter than `from-one` since you want that value to be `000` `00` `0` and then so on.

**Comment by argyleink** [comment]
good call.
thanks for loggin. 
might be able to trick the counter system but not having the first 2 contribute to increment, and then concat an extra 0 on them?

**Comment by Crisfole** [comment]
Yeah, alternatively explicitly set the triple and double zero contents, then do an explicit counter reset on the single zero?

I’d have fixed it but no one else was gonna feed the family ;)

**Comment by Crisfole** [comment]
Might need a way to demo the negative sizing too…unclear how that might be best shown… negative margin lacks visibility, but can be made clear

**Comment by Brian-Pob** [comment]
Just realized the counters go from 0-14 when it should be from 1-15 since size-0 doesn't exist.

For the negative size demo, I was also thinking that negative margin could be used. I whipped up a quick codepen to show it.

https://codepen.io/brian-pob/pen/vYMxewe

![Screenshot of codepen showing negative size demo](https://github.com/argyleink/open-props/assets/29676413/95356f51-3780-4337-8a76-db5d39b24870)

**Comment by Crisfole** [comment]
Uh, sizes 000, 00, *and* 0 exist…am I missing something?

**Comment by Brian-Pob** [comment]
I believe 0 does not exist. I'm basing this off the list of sizes.
![CleanShot 2024-03-20 at 21 11 24](https://github.com/argyleink/open-props/assets/29676413/da5ca874-15ca-4ee3-9bed-bbddfb28ac8c)

And when you look at the properties there is no `size-0`
![CleanShot 2024-03-20 at 21 12 20](https://github.com/argyleink/open-props/assets/29676413/a6293062-4310-4e3b-b54a-5cfebec5f690)

**Comment by argyleink** [comment]
since 000, 00 are negative values, there's no reason to show them! have the size visualization start at 1 `.from-one` like you did with gradients and its done?

Class should be added to
- sizes
- reading sizes
- headline sizes
- relative sizes

**Comment by Crisfole** [comment]
Ahh, missed the single 0 being missing, good catch
