### ISSUE TITLE
Media query conflict at "only" breakpoints

### ISSUE THREAD

**Issue by mobalti** [argyleink/open-props#486]
There is a potential conflict in the media queries "only" breakpoints. For example:

```css
@media (768px <= width <= 1024px);
@media (width >= 1024px);
```
To resolve this conflict, we can use the "<" operator instead of "<=" for the range's upper limit. This ensures screens with a width exactly at this point are not included.

```css
@media (768px <= width < 1024px);
@media (width >= 1024px);
```

**Comment by argyleink** [comment]
nice, yes, let's fix this!

a similar issue happened with the `--n-below` queries, and they got switched to not including `=`:

```css
@custom-media --xxl-only      (1440px <= width <= 1920px);
@custom-media --xxl-n-above   (width >= 1920px);
@custom-media --xxl-n-below   (width < 1920px); ⬅️
```

Let's align these, like you propose:

```css
@custom-media --xxl-only      (1440px <= width < 1920px);
@custom-media --xxl-n-above   (width >= 1920px);
@custom-media --xxl-n-below   (width < 1920px);
```

TODO:
- [ ] [update](https://github.com/argyleink/open-props/blob/main/src/props.media.js) xxs, xs, sm, md, lg, xl, and xxl `-only` queries to be just `<`
- [ ] update [docsite](https://github.com/argyleink/open-props/blob/main/docsite/index.html#L3368)
