### ISSUE TITLE
`<a>` negative margin in normalize

### ISSUE THREAD

**Issue by luwes** [argyleink/open-props#491]
I wanted to mention this because it took me a good half hour to figure out what was going on.
A navigation link was covering the borders of the parent, caused by the normalize styles.

Not sure what the intention is of those styles but it feels possibly out of place for normalizing styles. It does too much.

<img width="1253" alt="SCR-20240405-njib" src="https://github.com/argyleink/open-props/assets/360826/a7344cfd-23a2-4c7d-b16a-b459c1c4c1dc">

**Comment by argyleink** [comment]
fixed in `v1.7.2`
