### ISSUE TITLE
Typo in v2 forms

### ISSUE THREAD

**Issue by djmtype** [argyleink/open-props#524]
In v2 beta there's a typo in packs/forms/inputs.css on line 6. A space is needed.

**Comment by argyleink** [comment]
ty!

**Comment by argyleink** [comment]
do you need this published to the beta channel for use, or you cloning and reaching in?

**Comment by djmtype** [comment]
@argyleink I wasn't using the forms just yet. I just happened to take notice. I have it referenced from your Github repo in my package.json. `"open-props": "github:argyleink/open-props#2.0.0beta"`
