### ISSUE TITLE
color docs are incorrect

### ISSUE THREAD

**Issue by sangrepura** [argyleink/open-props#534]
I was using this page: https://opv2-beta.netlify.app/color/
but the instructions instruct to `@import "open-props/palette.css";` which does not exist

**Comment by sangrepura** [comment]
I finally found it here:
https://unpkg.com/open-props@2.0.0-beta.5/palette.css

**Comment by argyleink** [comment]
glad you found it! indeed the docs for v2 beta need work to be easier
