### ISSUE TITLE
Avoid bad practice in --safariONLY example

### ISSUE THREAD

**Issue by oscarmarcelo** [argyleink/open-props#77]
Considering the example for `--safariONLY`:
https://github.com/argyleink/open-props/blob/e1cf0c512ddec0aff56b41ba6cf4c694bdf57b7b/docsite/index.html#L2661-L2665

Although we all know that this is just an example, it's still not the best one, since in the end this custom property is still a hack that might break in the future __when__ CSS already has a native way of checking this specific case with `@supports (color: color(display-p3 1 1 1))`

Right now I don't have a suggestion interesting enough to give you, but will do as soon as I remember one.

**Comment by equinusocio** [comment]
Also, `safariONLY` is a not a `@media` at-rule but a `@supports` rule. The example above doesn't even works.

**Comment by equinusocio** [comment]
Also, shouldn't be `@supports (--safariONLY)` instead of `@media (--safariONLY)`?
