### ISSUE TITLE
Missing export

### ISSUE THREAD

**Issue by kucrut** [argyleink/open-props#96]
I was trying to import the normalize pack on a SvelteKit project which uses Vite from my `index.pcss` as demonstrated on the guide:

```css
@import "open-props/src/extra/normalize.css";
```

and got the error below:

```
[vite] Internal server error: Missing "./src/extra/normalize.css" export in "open-props" package
```

A quick search yields a previously reported issue: https://github.com/vitejs/vite/issues/1505

I can import the normalize pack using:

```
@import 'open-props/normalize';
```

... but that works only because `normalize` is defined in the package's `exports` field. To import other packs individually, one needs to use relative import syntax `@import '../../node_modules/open-props/...`.

**Comment by argyleink** [comment]
Ty for reporting! I can resolve this quickly

**Comment by argyleink** [comment]
it's now `@import "open-props/postcss/normalize";` 🙁
